company_name: pingix
root_zone: .ttu
github_username: 1nnu
node_exporter_port: 9100
backup_server_ip: 192.168.42.132
backup_server_name: "backup"
backup_server_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEu6pFFWyuRrl4WGFPQGElYN9txwTGm2wSntcpVAaN90
node_id: "{{ (ansible_port / 100) | int }}"
allowed_networks:
 - 192.168.42.0/23
 - 127.0.0.0/8
 - 172.17.0.0/16
dns_forwarders:
 - 1.1.1.1
 - 8.8.8.8
 - 9.9.9.9
uwsgi_socket: localhost:5000

# MYSQL
mysql_backup_host: "{{ groups['db_servers'] | reject('eq', mysql_host) | first | default(mysql_host) }}"
mysql_host: "{{ groups['db_servers'] | first}}"
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34306430346239326261333433363665636465626536613432336437663139633035663132646133
          3866306437666161373162333334613564326135323236310a326466333230323163666231663561
          34663564396231313137343339333735303238303563343730363961373337623262323234306565
          3636363465626330310a383066616163666336663166333235396664623231363539356563336365
          3537

# MYSQL exporter

mysql_exporter_user: mysql_exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38376233333534663065376439363061656363663134376664376430316164306339373334366134
          3634343462383732393536356637383331323531383463300a623031363764356230616237303665
          61663733303436383862316439326637626430633165393763313134336465663361643065373533
          3735646339303166330a386633386563616437313165353936323635326536383831383262636264
          33313532323564393433643062616334653661656233643236396639633334343636


# MYSQL REPLICATION
mysql_replication_user: mysql_replication
mysql_replication_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34626238306534626639333966656234343362623638646139376136333137643332316563383136
          6264363866356231303165633362353630353035326631630a653865613731313537623764346133
          38656134626662383764343162383561633035626235366633343130353332356439316631386436
          6237633131646166640a623366313734343130636332653466346133643734376636356239663165
          35316461316635663561356535343965383738386335373664346633333261316531

# GRAFANA
grafana_port: 3001
grafana_user: grafana
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35313162303863333539313736633264343838343465333966663366343933336437363233356561
          6235666362353561646236646234366638333837366535610a356665373665613631643862373433
          36643235306163393063306230656537373861333362656366663432373162383064393437616565
          6237313332376365300a643830646430613834336261363135383733656362633934663937323162
          3461

# AGAMA CLIENT

agama_client_user: agama-client
agama_client_application: agama-client
agama_port: 8001

# INFLUXDB

influxdb_agama_db_name: agama
influxdb_port: 8086