company_name: pingix
root_zone: .ttu
node_exporter_port: 9100
backup_server_ip: 192.168.42.132
backup_server_name: "backup"
backup_server_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEu6pFFWyuRrl4WGFPQGElYN9txwTGm2wSntcpVAaN90
grafana_port: 3000
allowed_networks:
 - 192.168.42.0/23
 - 127.0.0.0/8
dns_forwarders:
 - 1.1.1.1
 - 8.8.8.8
uwsgi_socket: localhost:5000

# MYSQL

mysql_host: 1nnu-2
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34306430346239326261333433363665636465626536613432336437663139633035663132646133
          3866306437666161373162333334613564326135323236310a326466333230323163666231663561
          34663564396231313137343339333735303238303563343730363961373337623262323234306565
          3636363465626330310a383066616163666336663166333235396664623231363539356563336365
          3537

# MYSQL exporter

mysql_exporter_user: mysql_exporter
mysql_exporter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38376233333534663065376439363061656363663134376664376430316164306339373334366134
          3634343462383732393536356637383331323531383463300a623031363764356230616237303665
          61663733303436383862316439326637626430633165393763313134336465663361643065373533
          3735646339303166330a386633386563616437313165353936323635326536383831383262636264
          33313532323564393433643062616334653661656233643236396639633334343636

# GRAFANA
grafana_user: grafana
grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35313162303863333539313736633264343838343465333966663366343933336437363233356561
          6235666362353561646236646234366638333837366535610a356665373665613631643862373433
          36643235306163393063306230656537373861333362656366663432373162383064393437616565
          6237313332376365300a643830646430613834336261363135383733656362633934663937323162
          3461

# AGAMA CLIENT

agama_client_user: agama-client
agama_client_application: agama-client

# INFLUXDB

influxdb_agama_db_name: agama
influxdb_port: 8086