uwsgi_socket: localhost:5000

mysql_host: 192.168.42.82
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34306430346239326261333433363665636465626536613432336437663139633035663132646133
          3866306437666161373162333334613564326135323236310a326466333230323163666231663561
          34663564396231313137343339333735303238303563343730363961373337623262323234306565
          3636363465626330310a383066616163666336663166333235396664623231363539356563336365
          3537